// <auto-generated />
using System;
using EmployeeManagmentSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagmentSystem.Migrations
{
    [DbContext(typeof(EmpManagmentContext))]
    [Migration("20220304211631_FirstInitial")]
    partial class FirstInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmployeeManagmentSystem.Data.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 3, 5, 1, 16, 30, 830, DateTimeKind.Local).AddTicks(9223));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2022, 3, 5, 1, 16, 30, 830, DateTimeKind.Local).AddTicks(9360),
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2022, 3, 5, 1, 16, 30, 830, DateTimeKind.Local).AddTicks(9362),
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2022, 3, 5, 1, 16, 30, 830, DateTimeKind.Local).AddTicks(9363),
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2022, 3, 5, 1, 16, 30, 830, DateTimeKind.Local).AddTicks(9364),
                            Name = "Economics"
                        });
                });

            modelBuilder.Entity("EmployeeManagmentSystem.Data.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 3, 5, 1, 16, 30, 830, DateTimeKind.Local).AddTicks(8251));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 3, 5, 1, 16, 30, 830, DateTimeKind.Local).AddTicks(8523),
                            DepartmentId = 1,
                            Name = "Kenan",
                            Surname = "Amirli"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2000, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 3, 5, 1, 16, 30, 830, DateTimeKind.Local).AddTicks(8526),
                            DepartmentId = 2,
                            Name = "Rufat",
                            Surname = "Qedirov"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2001, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 3, 5, 1, 16, 30, 830, DateTimeKind.Local).AddTicks(8527),
                            DepartmentId = 3,
                            Name = "Fazil",
                            Surname = "Amirli"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1992, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 3, 5, 1, 16, 30, 830, DateTimeKind.Local).AddTicks(8529),
                            DepartmentId = 4,
                            Name = "Qara",
                            Surname = "Humbatov"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(2003, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 3, 5, 1, 16, 30, 830, DateTimeKind.Local).AddTicks(8530),
                            DepartmentId = 4,
                            Name = "Nurlan",
                            Surname = "Ramazanov"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1998, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 3, 5, 1, 16, 30, 830, DateTimeKind.Local).AddTicks(8532),
                            DepartmentId = 2,
                            Name = "Vasif",
                            Surname = "Hasanzadeh"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 3, 5, 1, 16, 30, 830, DateTimeKind.Local).AddTicks(8533),
                            DepartmentId = 2,
                            Name = "Turqay",
                            Surname = "Abdullayef"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(2004, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 3, 5, 1, 16, 30, 830, DateTimeKind.Local).AddTicks(8534),
                            DepartmentId = 1,
                            Name = "Turqay",
                            Surname = "Osmanli"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(2000, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 3, 5, 1, 16, 30, 830, DateTimeKind.Local).AddTicks(8535),
                            DepartmentId = 1,
                            Name = "Ehmed",
                            Surname = "Qarayev"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(2000, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 3, 5, 1, 16, 30, 830, DateTimeKind.Local).AddTicks(8537),
                            DepartmentId = 1,
                            Name = "Qedir",
                            Surname = "Babayev"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(2007, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 3, 5, 1, 16, 30, 830, DateTimeKind.Local).AddTicks(8538),
                            DepartmentId = 3,
                            Name = "Hebib",
                            Surname = "Amirli"
                        });
                });

            modelBuilder.Entity("EmployeeManagmentSystem.Data.Entities.Employee", b =>
                {
                    b.HasOne("EmployeeManagmentSystem.Data.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
